name: tf2-gpu

dependencies:
  - python
  - pip
  - matplotlib
  - cudnn
  - cudatoolkit==10.1.243
  - swig
  - git
  - pip:
    - opencv-python
    - tensorflow-gpu
    - tensorflow
    - lxml
    - tqdm
    - numba
    - argparse
    - dill
    - fire
    - psutil
    - requests
    - scikit-image
    - scipy
    - slidingwindow
    - git+https://github.com/adrianc-a/tf-slim.git@remove_contrib
    - pycocotools-windows
    - -e .
